name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_KAKAO_MAP_KEY =${{ secrets.REACT_APP_KAKAO_MAP_KEY }} >> .env
      - name: Build static site
        run: yarn install && yarn build
      - name: Deploy static site to S3 bucket
        run: yarn deploy
